# generated by datamodel-codegen:
#   filename:  CustomViewForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Model:
    index: str
    type: Literal['LIST', 'CALENDAR', 'CUSTOM']
    pager: Optional[str] = None
    name: Optional[str] = None
    html: Optional[str] = None
    sort: Optional[str] = None
    filterCond: Optional[str] = None
    device: Optional[Literal['DESKTOP', 'ANY']] = None
    builtinType: Optional[Literal['ASSIGNEE']] = None
