# generated by datamodel-codegen:
#   filename:  IconFileForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class File:
    fileKey: str
    size: Optional[str] = None
    name: Optional[str] = None
    contentType: Optional[str] = None


@dataclass
class Model:
    file: File
    type: Literal['FILE', 'PRESET']
