# generated by datamodel-codegen:
#   filename:  ListViewForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Optional


@dataclass
class Model:
    index: str
    type: Literal['LIST', 'CALENDAR', 'CUSTOM']
    name: Optional[str] = None
    sort: Optional[str] = None
    fields: Optional[List[str]] = None
    filterCond: Optional[str] = None
    builtinType: Optional[Literal['ASSIGNEE']] = None
