# generated by datamodel-codegen:
#   filename:  NumberPrecision
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Model:
    roundingMode: Optional[Literal['HALF_EVEN', 'UP', 'DOWN']] = None
    decimalPlaces: Optional[str] = None
    digits: Optional[str] = None
