# generated by datamodel-codegen:
#   filename:  PeriodicReport
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Union

from . import PeriodDay, PeriodHour, PeriodMonth, PeriodQuarter, PeriodWeek, PeriodYear


@dataclass
class Model:
    period: Optional[
        Union[
            PeriodYear.Model,
            PeriodQuarter.Model,
            PeriodMonth.Model,
            PeriodWeek.Model,
            PeriodDay.Model,
            PeriodHour.Model,
        ]
    ] = None
    active: Optional[str] = None
