# generated by datamodel-codegen:
#   filename:  RecordsStatusPutForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List

from . import RecordsStatusPutFormRecord


@dataclass
class Model:
    app: str
    records: List[RecordsStatusPutFormRecord.Model]
