# generated by datamodel-codegen:
#   filename:  RecordsDeleteForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class Model:
    app: str
    ids: List[str]
    revisions: Optional[List[str]] = None
