# generated by datamodel-codegen:
#   filename:  RecordsPostOutputForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class Model:
    ids: Optional[List[str]] = None
    revisions: Optional[List[str]] = None
