# generated by datamodel-codegen:
#   filename:  Sort
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass
class Model:
    by: Literal['TOTAL', 'GROUP1', 'GROUP2', 'GROUP3']
    order: Literal['ASC', 'DESC']
