[project]
name = "kinpy"
version = "0.1.0"
description = "A simple Python wrapper for the Kin API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[tool.setuptools.packages.find]
where = ["src"]