# generated by datamodel-codegen:
#   filename:  json-schemas
#   timestamp: 2025-02-05T13:37:17+00:00

"""Gen Command
datamodel-codegen 
    --input json-schemas 
    --output models 
    --output-model-type dataclasses.dataclass 
    --use-title-as-name 
    --use-schema-description 
    --collapse-root-models 
    --use-unique-items-as-set 
    --use-one-literal-as-default 
    --additional-imports datetime.datetime 
    --enum-field-as-literal all
"""