# generated by datamodel-codegen:
#   filename:  Action
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Union

from . import Entity, FieldMapping, UrlMapping


@dataclass
class DestApp:
    app: Optional[str] = None
    code: Optional[str] = None


@dataclass
class Model:
    mappings: Optional[List[Union[UrlMapping.Model, FieldMapping.Model]]] = None
    entities: Optional[List[Entity.Model]] = None
    name: Optional[str] = None
    index: Optional[str] = None
    id: Optional[str] = None
    destApp: Optional[DestApp] = None
