# generated by datamodel-codegen:
#   filename:  ActionForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    name: Optional[str] = None
    from_: Optional[str] = None
    to: Optional[str] = None
    filterCond: Optional[str] = None
