# generated by datamodel-codegen:
#   filename:  AppForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Creator:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Modifier:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Space:
    name: Optional[str] = None
    id: Optional[str] = None


@dataclass
class Model:
    fieldCount: Optional[str] = None
    creator: Optional[Creator] = None
    customized: Optional[bool] = None
    modifiedAt: Optional[str] = None
    recordCount: Optional[str] = None
    modifier: Optional[Modifier] = None
    space: Optional[Space] = None
    recordUpdatedAt: Optional[str] = None
    createdAt: Optional[str] = None
    dailyRequestCount: Optional[str] = None
    appGroup: Optional[str] = None
    storageUsage: Optional[str] = None
    name: Optional[str] = None
    id: Optional[str] = None
    status: Optional[Literal['NOT_ACTIVATED', 'ACTIVATED', 'CHANGED']] = None
