# generated by datamodel-codegen:
#   filename:  AttachedApp
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Creator:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Modifier:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Model:
    threadId: Optional[str] = None
    createdAt: Optional[str] = None
    creator: Optional[Creator] = None
    code: Optional[str] = None
    modifiedAt: Optional[str] = None
    appId: Optional[str] = None
    modifier: Optional[Modifier] = None
    name: Optional[str] = None
    description: Optional[str] = None
