# generated by datamodel-codegen:
#   filename:  CalcSimpleProperties
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Model:
    noLabel: Optional[str] = None
    unit: Optional[str] = None
    expression: Optional[str] = None
    code: Optional[str] = None
    format: Optional[
        Literal[
            'NUMBER',
            'NUMBER_DIGIT',
            'DATETIME',
            'DATE',
            'TIME',
            'HOUR_MINUTE',
            'DAY_HOUR_MINUTE',
        ]
    ] = None
    unitPosition: Optional[str] = None
    label: Optional[str] = None
    type: Optional[
        Literal[
            'LABEL',
            'SPACER',
            'HR',
            'CREATED_TIME',
            'CREATOR',
            'DATE',
            'DATETIME',
            'NUMBER',
            'CALC',
            'RICH_TEXT',
            'FILE',
            'UPDATED_TIME',
            'MODIFIER',
            'CHECK_BOX',
            'MULTI_LINE_TEXT',
            'MULTI_SELECT',
            'RECORD_NUMBER',
            'RADIO_BUTTON',
            'SINGLE_LINE_TEXT',
            'DROP_DOWN',
            'SUBTABLE',
            'TIME',
            'USER_SELECT',
            'ORGANIZATION_SELECT',
            'GROUP_SELECT',
            'REFERENCE_TABLE',
            'LINK',
        ]
    ] = None
    displayScale: Optional[str] = None
    hideExpression: Optional[str] = None
    required: Optional[str] = None
