# generated by datamodel-codegen:
#   filename:  CalendarViewOutputForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Model:
    date: Optional[str] = None
    name: Optional[str] = None
    index: Optional[str] = None
    id: Optional[str] = None
    sort: Optional[str] = None
    title: Optional[str] = None
    type: Optional[Literal['LIST', 'CALENDAR', 'CUSTOM']] = None
    filterCond: Optional[str] = None
