# generated by datamodel-codegen:
#   filename:  CommentOutputForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from . import MentionOutputForm


@dataclass
class Creator:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Model:
    createdAt: Optional[str] = None
    creator: Optional[Creator] = None
    mentions: Optional[List[MentionOutputForm.Model]] = None
    id: Optional[str] = None
    text: Optional[str] = None
