# generated by datamodel-codegen:
#   filename:  CustomViewOutputForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Model:
    pager: Optional[bool] = None
    name: Optional[str] = None
    index: Optional[str] = None
    html: Optional[str] = None
    id: Optional[str] = None
    sort: Optional[str] = None
    type: Optional[Literal['LIST', 'CALENDAR', 'CUSTOM']] = None
    filterCond: Optional[str] = None
    device: Optional[Literal['DESKTOP', 'ANY']] = None
