# generated by datamodel-codegen:
#   filename:  EntityRightForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Entity:
    type: Literal['USER', 'GROUP', 'ORGANIZATION', 'FIELD_ENTITY']
    code: Optional[str] = None


@dataclass
class Model:
    entity: Entity
    viewable: Optional[str] = None
    editable: Optional[str] = None
    deletable: Optional[str] = None
    includeSubs: Optional[str] = None
