# generated by datamodel-codegen:
#   filename:  FieldRightEntity
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass
class Entity:
    type: Literal['USER', 'GROUP', 'ORGANIZATION', 'FIELD_ENTITY']
    code: Optional[str] = None


@dataclass
class Model:
    accessibility: Literal['WRITE', 'READ', 'NONE']
    entity: Entity
    includeSubs: Optional[str] = None
