# generated by datamodel-codegen:
#   filename:  GroupRow
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Optional

from . import Row


@dataclass
class Model:
    code: str
    type: Literal['ROW', 'SUBTABLE', 'GROUP']
    layout: Optional[List[Row.Model]] = None
