# generated by datamodel-codegen:
#   filename:  GuestUserForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    password: str
    code: str
    timezone: str
    name: str
    division: Optional[str] = None
    callto: Optional[str] = None
    image: Optional[str] = None
    phone: Optional[str] = None
    surNameReading: Optional[str] = None
    company: Optional[str] = None
    locale: Optional[str] = None
    givenNameReading: Optional[str] = None
