# generated by datamodel-codegen:
#   filename:  Notification
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Union

from . import Target, TimingAbsolute, TimingRelative


@dataclass
class Model:
    timing: Optional[Union[TimingRelative.Model, TimingAbsolute.Model]] = None
    filterCond: Optional[str] = None
    title: Optional[str] = None
    targets: Optional[List[Target.Model]] = None
