# generated by datamodel-codegen:
#   filename:  PeriodYear
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass
class Model:
    month: str
    dayOfMonth: str
    time: str
    every: Literal['YEAR', 'QUARTER', 'MONTH', 'WEEK', 'DAY', 'HOUR']
