# generated by datamodel-codegen:
#   filename:  PeriodQuarter
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass
class Model:
    dayOfMonth: str
    pattern: Literal['JAN_APR_JUL_OCT', 'FEB_MAY_AUG_NOV', 'MAR_JUN_SEP_DEC']
    time: str
    every: Literal['YEAR', 'QUARTER', 'MONTH', 'WEEK', 'DAY', 'HOUR']
