# generated by datamodel-codegen:
#   filename:  PeriodWeek
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass
class Model:
    dayOfWeek: Literal[
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'
    ]
    time: str
    every: Literal['YEAR', 'QUARTER', 'MONTH', 'WEEK', 'DAY', 'HOUR']
