# generated by datamodel-codegen:
#   filename:  PluginForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    name: Optional[str] = None
    id: Optional[str] = None
    enabled: Optional[bool] = None
