# generated by datamodel-codegen:
#   filename:  RecordsPutOutputForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from . import RecordBean


@dataclass
class Model:
    records: Optional[List[Dict[str, RecordBean.Model]]] = None
