# generated by datamodel-codegen:
#   filename:  RecordsPutForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from . import RecordForm


@dataclass
class Model:
    app: str
    records: List[RecordForm.Model]
    upsert: Optional[str] = None
