# generated by datamodel-codegen:
#   filename:  RecordPostOutputForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    id: Optional[str] = None
    revision: Optional[str] = None
