# generated by datamodel-codegen:
#   filename:  Report
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Optional, Union

from . import FieldAggregation, Group, PeriodicReport, RecordAggregation, Sort


@dataclass
class Model:
    chartType: Literal[
        'PIE',
        'LINE',
        'SPLINE',
        'TABLE',
        'PIVOT_TABLE',
        'BAR',
        'COLUMN',
        'AREA',
        'SPLINE_AREA',
    ]
    index: str
    periodicReport: Optional[PeriodicReport.Model] = None
    name: Optional[str] = None
    groups: Optional[List[Group.Model]] = None
    filterCond: Optional[str] = None
    aggregations: Optional[
        List[Union[RecordAggregation.Model, FieldAggregation.Model]]
    ] = None
    sorts: Optional[List[Sort.Model]] = None
