# generated by datamodel-codegen:
#   filename:  RightForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from . import EntityRightForm


@dataclass
class Model:
    entities: List[EntityRightForm.Model]
    filterCond: Optional[str] = None
