# generated by datamodel-codegen:
#   filename:  SpaceForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Creator:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Modifier:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class Model:
    createdAt: Optional[str] = None
    creator: Optional[Creator] = None
    isGuest: Optional[bool] = None
    modifiedAt: Optional[str] = None
    memberCount: Optional[str] = None
    modifier: Optional[Modifier] = None
    name: Optional[str] = None
    id: Optional[str] = None
    isPrivate: Optional[bool] = None
    administratorCount: Optional[str] = None
