# generated by datamodel-codegen:
#   filename:  StateForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Optional

from . import AssigneeEntityForm


@dataclass
class Assignee:
    entities: Optional[List[AssigneeEntityForm.Model]] = None
    type: Optional[Literal['ONE', 'ALL', 'ANY']] = None


@dataclass
class Model:
    name: Optional[str] = None
    index: Optional[str] = None
    assignee: Optional[Assignee] = None
