# generated by datamodel-codegen:
#   filename:  SubtableRow
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Union

from . import (
    CalcField,
    CreatedAtField,
    CreatorField,
    DateField,
    DatetimeField,
    DecimalField,
    EditorField,
    FileField,
    HrField,
    LabelField,
    LinkField,
    LookupField,
    ModifiedAtField,
    ModifierField,
    MultipleCheckField,
    MultipleLineTextField,
    MultipleSelectField,
    RecordIdField,
    ReferenceTableField,
    SingleCheckField,
    SingleLineTextField,
    SingleSelectField,
    SpacerField,
    TimeField,
    UserSelectField,
)


@dataclass
class Model:
    code: str
    fields: List[
        Union[
            LabelField.Model,
            SingleLineTextField.Model,
            MultipleLineTextField.Model,
            EditorField.Model,
            DecimalField.Model,
            CalcField.Model,
            MultipleCheckField.Model,
            SingleCheckField.Model,
            SingleSelectField.Model,
            MultipleSelectField.Model,
            FileField.Model,
            DateField.Model,
            DatetimeField.Model,
            TimeField.Model,
            UserSelectField.Model,
            LinkField.Model,
            LookupField.Model,
            ReferenceTableField.Model,
            SpacerField.Model,
            HrField.Model,
            RecordIdField.Model,
            CreatorField.Model,
            CreatedAtField.Model,
            ModifierField.Model,
            ModifiedAtField.Model,
        ]
    ]
    type: Literal['ROW', 'SUBTABLE', 'GROUP']
