# generated by datamodel-codegen:
#   filename:  SubTableLayoutProperties
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Optional, Union

from . import (
    BultinProperties,
    CalcSimpleProperties,
    DateSimpleProperties,
    DatetimeSimpleProperties,
    DecimalSimpleProperties,
    EditorSimpleProperties,
    FileSimpleProperties,
    GroupSelectSimpleProperties,
    LabelProperties,
    LayoutProperties,
    LinkSimpleProperties,
    LookupSimpleProperties,
    MultipleLineTextSimpleProperties,
    MultipleSelectSimpleProperties,
    OrganizationSelectSimpleProperties,
    ReferenceTableLayoutProperties,
    SingleLineTextSimpleProperties,
    SingleSelectSimpleProperties,
    SpacerProperties,
    TimeSimpleProperties,
    UserSelectSimpleProperties,
)


@dataclass
class Model:
    noLabel: Optional[str] = None
    code: Optional[str] = None
    label: Optional[str] = None
    fields: Optional[
        List[
            Union[
                LayoutProperties.Model,
                LabelProperties.Model,
                BultinProperties.Model,
                CalcSimpleProperties.Model,
                DateSimpleProperties.Model,
                DatetimeSimpleProperties.Model,
                DecimalSimpleProperties.Model,
                EditorSimpleProperties.Model,
                FileSimpleProperties.Model,
                LinkSimpleProperties.Model,
                MultipleLineTextSimpleProperties.Model,
                MultipleSelectSimpleProperties.Model,
                SingleLineTextSimpleProperties.Model,
                SingleSelectSimpleProperties.Model,
                TimeSimpleProperties.Model,
                UserSelectSimpleProperties.Model,
                OrganizationSelectSimpleProperties.Model,
                GroupSelectSimpleProperties.Model,
                LookupSimpleProperties.Model,
                ReferenceTableLayoutProperties.Model,
                Model,
                SpacerProperties.Model,
            ]
        ]
    ] = None
    type: Optional[
        Literal[
            'LABEL',
            'SPACER',
            'HR',
            'CREATED_TIME',
            'CREATOR',
            'DATE',
            'DATETIME',
            'NUMBER',
            'CALC',
            'RICH_TEXT',
            'FILE',
            'UPDATED_TIME',
            'MODIFIER',
            'CHECK_BOX',
            'MULTI_LINE_TEXT',
            'MULTI_SELECT',
            'RECORD_NUMBER',
            'RADIO_BUTTON',
            'SINGLE_LINE_TEXT',
            'DROP_DOWN',
            'SUBTABLE',
            'TIME',
            'USER_SELECT',
            'ORGANIZATION_SELECT',
            'GROUP_SELECT',
            'REFERENCE_TABLE',
            'LINK',
        ]
    ] = None
