# generated by datamodel-codegen:
#   filename:  TableForm
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Literal, Optional, Union

from . import (
    CalcFieldForm,
    CategoryFieldForm,
    DateFieldForm,
    DatetimeFieldForm,
    DecimalFieldForm,
    EditorFieldForm,
    FileFieldForm,
    GroupFieldForm,
    GroupSelectFieldForm,
    LinkFieldForm,
    LookupFieldForm,
    ModifiedAtFieldForm,
    ModifierFieldForm,
    MultipleCheckFieldForm,
    MultipleLineTextFieldForm,
    MultipleSelectFieldForm,
    OrganizationSelectFieldForm,
    RecordIdFieldForm,
    ReferenceTableFieldForm,
    SingleCheckFieldForm,
    SingleLineTextFieldForm,
    SingleSelectFieldForm,
    StatusAssigneeFieldForm,
    StatusFieldForm,
    TimeFieldForm,
    UserSelectFieldForm,
)


@dataclass
class Model:
    type: Literal[
        'CALC',
        'CATEGORY',
        'CHECK_BOX',
        'CREATED_TIME',
        'CREATOR',
        'DATE',
        'DATETIME',
        'DROP_DOWN',
        'FILE',
        'GROUP',
        'GROUP_SELECT',
        'LINK',
        'MODIFIER',
        'MULTI_LINE_TEXT',
        'MULTI_SELECT',
        'NUMBER',
        'ORGANIZATION_SELECT',
        'RADIO_BUTTON',
        'RECORD_NUMBER',
        'REFERENCE_TABLE',
        'RICH_TEXT',
        'SINGLE_LINE_TEXT',
        'STATUS',
        'STATUS_ASSIGNEE',
        'SUBTABLE',
        'TIME',
        'UPDATED_TIME',
        'USER_SELECT',
    ]
    noLabel: Optional[bool] = None
    code: Optional[str] = None
    label: Optional[str] = None
    fields: Optional[
        Dict[
            str,
            Union[
                CalcFieldForm.Model,
                CategoryFieldForm.Model,
                DateFieldForm.Model,
                DatetimeFieldForm.Model,
                DecimalFieldForm.Model,
                EditorFieldForm.Model,
                FileFieldForm.Model,
                GroupFieldForm.Model,
                GroupSelectFieldForm.Model,
                LinkFieldForm.Model,
                LookupFieldForm.Model,
                ModifiedAtFieldForm.Model,
                ModifierFieldForm.Model,
                MultipleCheckFieldForm.Model,
                MultipleLineTextFieldForm.Model,
                MultipleSelectFieldForm.Model,
                OrganizationSelectFieldForm.Model,
                RecordIdFieldForm.Model,
                ReferenceTableFieldForm.Model,
                SingleCheckFieldForm.Model,
                SingleLineTextFieldForm.Model,
                SingleSelectFieldForm.Model,
                StatusAssigneeFieldForm.Model,
                StatusFieldForm.Model,
                Model,
                TimeFieldForm.Model,
                UserSelectFieldForm.Model,
            ],
        ]
    ] = None
