# generated by datamodel-codegen:
#   filename:  TimingRelative
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    hoursLater: Optional[str] = None
    code: Optional[str] = None
    daysLater: Optional[str] = None
