# generated by datamodel-codegen:
#   filename:  UserBean
#   timestamp: 2025-02-05T13:42:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Entity:
    code: Optional[str] = None
    type: Optional[str] = None


@dataclass
class Model:
    isImplicit: Optional[bool] = None
    isAdmin: Optional[bool] = None
    entity: Optional[Entity] = None
